/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REVERSE_H_RPCGEN
#define _REVERSE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REVERSEPROGRAM 12345678
#define REVERSEVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define reverse 1
extern  int * reverse_1(int *, CLIENT *);
extern  int * reverse_1_svc(int *, struct svc_req *);
extern int reverseprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define reverse 1
extern  int * reverse_1();
extern  int * reverse_1_svc();
extern int reverseprogram_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REVERSE_H_RPCGEN */
