/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uppercase.h"

bool_t
xdr_inputString (XDR *xdrs, inputString *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->inWord, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_outString (XDR *xdrs, outString *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->outWord, ~0))
		 return FALSE;
	return TRUE;
}
