/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "uppercase.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct outString *
lowertoupper_1(struct inputString *argp, CLIENT *clnt)
{
	static struct outString clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, lowertoupper,
		(xdrproc_t) xdr_inputString, (caddr_t) argp,
		(xdrproc_t) xdr_outString, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
