/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARITHOP_H_RPCGEN
#define _ARITHOP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputInfo {
	int num_1;
	int num_2;
	int num_4;
	int option;
};
typedef struct inputInfo inputInfo;

struct outputInfo {
	int resultValue;
	float floatResultValue;
};
typedef struct outputInfo outputInfo;

#define ARITHMETICPROGRAM 55555555
#define ARITHMETICVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define performoperation 1
extern  struct outputInfo * performoperation_1(inputInfo *, CLIENT *);
extern  struct outputInfo * performoperation_1_svc(inputInfo *, struct svc_req *);
extern int arithmeticprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define performoperation 1
extern  struct outputInfo * performoperation_1();
extern  struct outputInfo * performoperation_1_svc();
extern int arithmeticprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputInfo (XDR *, inputInfo*);
extern  bool_t xdr_outputInfo (XDR *, outputInfo*);

#else /* K&R C */
extern bool_t xdr_inputInfo ();
extern bool_t xdr_outputInfo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARITHOP_H_RPCGEN */
