/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "arithOP.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct outputInfo *
performoperation_1(inputInfo *argp, CLIENT *clnt)
{
	static struct outputInfo clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, performoperation,
		(xdrproc_t) xdr_inputInfo, (caddr_t) argp,
		(xdrproc_t) xdr_outputInfo, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
